children:
  - Organism.Header:
      children:
        - Molecule.Navigation:
            children:
              - Atom.Button:
                  events:
                    - touch
                  path: leftbar
                  icon: menu
            style: left
        - Atom.Heading:
            size: h1
            value: SubView
  - Molecule.Navigation:
      children:
        - Atom.Button:
            style: active
            events:
              - touch
            callbacks:
              - onNewVideos
            text: New Videos
        - Atom.Button:
            events:
              - touch
            callbacks:
              - onSubscriptions
            text: Subscriptions
        - Atom.Button:
            events:
              - touch
            callbacks:
              - onSearch
            text: Search
  - Organism.Section:
      children:
        - Molecule.List:
            children:
              - Atom.Li:
                  image: "http://i.ytimg.com/vi_webp/t6gVX6QtIDU/mqdefault.webp"
                  text: GOD OF WAR 3 - Episodio 7 - Kratos el amante
                  description: alexelcapo
              - Atom.Li:
                  description: alexelcapo
                  text: CASTLE OF ILLUSION - PC (COMPLETO)
                  image: "http://i.ytimg.com/vi_webp/qw2iRkE_Q6Y/mqdefault.webp"
                  style: align center
      id: new
  - Organism.Section:
      children:
        - Molecule.List:
            children:
              - Atom.Li:
                  image: "https://yt3.ggpht.com/-pYdCY4UeA_0/AAAAAAAAAAI/AAAAAAAAAAA/bJT-1w3ml1k/s100-c-k-no/photo.jpg"
                  text: alexelcapo
      id: subscriptions
  - Organism.Section:
      children:
        - Molecule.Form:
            children:
              - Atom.Input:
                  type: text
                  name: search_text
                  placeholder: ...
              - Atom.Button:
                  events:
                    - touch
                  icon: search
            events:
              - submit
        - Molecule.List:
            children:
              - Atom.Li: {}
      id: search
id: app
